-- local M = {}
--
-- local defaults = require "formatter.defaults"
-- local util = require "formatter.util"
--
-- -- M.uncrustify = util.withl(defaults.uncrustify, "CPP")
--
-- M.clangformat = util.copyf(defaults.clangformat, "CPP")
--
-- -- M.astyle = util.withl(defaults.astyle, "c")
--
-- return M
